name: Publish Python 🐍 distributions 📦 to PyPI

on:
  release:
    types:
      - published

jobs:
  build-n-publish-pypi:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install packaging libraries
        run: |
          python -m pip install flit
      - name: Build a binary wheel and a source tarball
        run: |
          python -m flit build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: __PYPI_API_TOKEN__
